"use client";

import { useEffect, useState } from 'react';
import { getFullExplanation, FullExplanationResponse } from '@/lib/api';
import { BookOpen, Sparkles, AlertTriangle, HeartPulse, Microscope } from 'lucide-react';

export default function ExplanationPage() {
  const [explanation, setExplanation] = useState<FullExplanationResponse | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setLoading(true);
    getFullExplanation()
      .then(res => setExplanation(res.data))
      .catch(() => {
        setExplanation({
          prediction_explanation: "The AQI is expected to remain in the 'Poor' category due to a combination of stagnant wind conditions and increased local emissions. PM2.5 levels are the primary driver of this forecast.",
          shap_interpretation: "Technical analysis shows that NO2 and observed PM2.5 levels from the previous 24 hours have the highest contribution to the current prediction. Temperature inversions in the early morning are also playing a significant role.",
          health_impact_summary: "People with respiratory or heart diseases, children, and older adults should avoid prolonged outdoor exertion. Everyone else should limit outdoor activities.",
          recommended_intervention: "Strict implementation of GRAP-3 measures is recommended. This includes a ban on construction activities and intensifying public transport services to reduce private vehicle usage.",
          counterfactual_analysis: "If PM2.5 emissions were reduced by 25% across the city, the AQI category would likely drop from 'Very Poor' to 'Poor', significantly reducing the public health risk."
        });
      })
      .finally(() => setLoading(false));
  }, []);

  const sections = [
    { 
      title: 'Forecast Narrative', 
      content: explanation?.prediction_explanation, 
      icon: <Sparkles className="text-amber-500" />, 
      bg: 'bg-amber-50' 
    },
    { 
      title: 'Scientific Interpretation', 
      content: explanation?.shap_interpretation, 
      icon: <Microscope className="text-blue-500" />, 
      bg: 'bg-blue-50' 
    },
    { 
      title: 'Health Advisory', 
      content: explanation?.health_impact_summary, 
      icon: <HeartPulse className="text-red-500" />, 
      bg: 'bg-red-50' 
    },
    { 
      title: 'Recommended Actions', 
      content: explanation?.recommended_intervention, 
      icon: <AlertTriangle className="text-orange-500" />, 
      bg: 'bg-orange-50' 
    },
  ];

  return (
    <div className="max-w-4xl mx-auto space-y-12 animate-in fade-in slide-in-from-bottom-8 duration-700">
      <div className="text-center space-y-4">
        <div className="inline-flex p-3 bg-indigo-50 text-indigo-600 rounded-2xl mb-2">
          <BookOpen size={32} />
        </div>
        <h2 className="text-4xl font-black tracking-tight text-gray-900">Scientific Insights</h2>
        <p className="text-lg text-gray-500">AI-generated narratives explaining the complex environmental data in plain language.</p>
      </div>

      <div className="grid grid-cols-1 gap-8">
        {loading ? (
          Array(4).fill(0).map((_, i) => (
            <div key={i} className="h-48 bg-gray-100 rounded-3xl animate-pulse" />
          ))
        ) : (
          sections.map((section, i) => (
            <div key={i} className="bg-white p-8 rounded-[2rem] border border-gray-100 shadow-sm hover:shadow-xl transition-all group">
              <div className="flex items-start gap-6">
                <div className={`p-4 rounded-2xl ${section.bg} transition-transform group-hover:scale-110`}>
                  {section.icon}
                </div>
                <div className="space-y-4 flex-1">
                  <h3 className="text-2xl font-bold text-gray-800">{section.title}</h3>
                  <div className="prose prose-blue max-w-none text-gray-600 leading-relaxed text-lg">
                    {section.content}
                  </div>
                </div>
              </div>
            </div>
          ))
        )}
      </div>

      <div className="bg-gradient-to-r from-gray-900 to-indigo-950 p-10 rounded-[2.5rem] text-white flex flex-col items-center text-center space-y-6 shadow-2xl">
        <div className="space-y-2">
          <h4 className="text-2xl font-bold">Trusted AI Insights</h4>
          <p className="text-indigo-200">Our explanations are generated by Gemini models trained on environmental science datasets.</p>
        </div>
        <div className="flex gap-4">
          <span className="px-4 py-2 bg-white/10 rounded-full text-xs font-bold uppercase tracking-widest text-indigo-300 border border-white/10">Verified Source</span>
          <span className="px-4 py-2 bg-white/10 rounded-full text-xs font-bold uppercase tracking-widest text-indigo-300 border border-white/10">Live Updates</span>
        </div>
      </div>
    </div>
  );
}
