# agents/context_builder.py

import json
from config import LATEST_RESULT_PATH

def load_result() -> dict:
    with open(LATEST_RESULT_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


# ─────────────────────────────────────────────
# PUBLIC AGENT CONTEXT
# Simplified — no raw SHAP numbers, no jargon
# ─────────────────────────────────────────────

def build_public_context(result: dict) -> str:
    preds       = result["predictions"]
    explanation = result["explanation"]
    date        = result["date"]

    lines = [
        f"=== TODAY'S AIR QUALITY DATA (Date: {date}) ===",
        "",
        "FORECAST FOR NEXT 3 DAYS:"
    ]

    for region, vals in preds["regions"].items():
        lines.append(
            f"• {region}: "
            f"Tomorrow = {vals['day_1']} AQI ({vals['category'][0]}), "
            f"Day after = {vals['day_2']} AQI ({vals['category'][1]}), "
            f"3 days ahead = {vals['day_3']} AQI ({vals['category'][2]})"
        )

    lines += [
        "",
        "AQI CATEGORIES (for reference):",
        "0–50 = Good | 51–100 = Satisfactory | 101–200 = Moderate",
        "201–300 = Poor | 301–400 = Very Poor | 401–500 = Severe",
        "",
        "WHAT IS CAUSING TODAY'S POLLUTION (plain language):",
        explanation["prediction_explanation"][:600],
        "",
        "HEALTH IMPACT SUMMARY:",
        explanation["health_impact_summary"],
        "",
        "BEST IMPROVEMENT POSSIBLE:",
        explanation["recommended_intervention"][:300],
    ]

    return "\n".join(lines)


# ─────────────────────────────────────────────
# POLICY AGENT CONTEXT
# Full data — SHAP values, all CF scenarios,
# complete scientific explanation
# ─────────────────────────────────────────────

def build_policy_context(result: dict) -> str:
    preds       = result["predictions"]
    shap        = result["shap"]
    cf          = result["counterfactuals"]
    explanation = result["explanation"]
    date        = result["date"]

    lines = [
        f"=== DELHI AQI TECHNICAL BRIEFING (Date: {date}) ===",
        "",
        "── REGION-WISE 3-DAY PREDICTIONS ──"
    ]

    for region, vals in preds["regions"].items():
        d1, d2, d3 = vals['day_1'], vals['day_2'], vals['day_3']
        trend = "↑ WORSENING" if d3 > d1 + 10 else ("↓ IMPROVING" if d3 < d1 - 10 else "→ STABLE")
        lines.append(
            f"• {region}: Day+1={d1} ({vals['category'][0]}), "
            f"Day+2={d2} ({vals['category'][1]}), "
            f"Day+3={d3} ({vals['category'][2]}) | Trend: {trend}"
        )

    lines += ["", "── SHAP FEATURE DRIVERS (Day+1, per region) ──"]
    for entry in shap:
        lines.append(
            f"\n{entry['region']} | "
            f"Base={entry['base_value']:.1f} → Predicted={entry['predicted_value']}"
        )
        for feat in entry["top_features"]:
            direction = "↑ increases AQI" if feat["shap_value"] > 0 else "↓ decreases AQI"
            lines.append(
                f"  {feat['feature']}: value={feat['actual_value']}, "
                f"SHAP={feat['shap_value']:+.2f} ({direction})"
            )

    lines += ["", "── COUNTERFACTUAL INTERVENTION SCENARIOS ──"]
    for entry in cf:
        lines.append(
            f"\n{entry['region']} | "
            f"Original AQI: {entry['original_day1_aqi']} ({entry['original_category']})"
        )
        for s in entry["scenarios"]:
            features_list = ", ".join(s['feature_changes'].keys())
            lines.append(
                f"  [{s['type'].upper()}] {s['name']}: "
                f"Vary {features_list} → "
                f"New AQI={s['new_aqi']} ({s['new_category']}) | "
                f"Reduction={s['aqi_reduction']} pts ({s['percent_improvement']})"
            )

    lines += [
        "",
        "── SCIENTIFIC ANALYSIS (Pre-generated by Phase 6) ──",
        "",
        "FORECAST EXPLANATION:",
        explanation["prediction_explanation"],
        "",
        "SHAP INTERPRETATION:",
        explanation["shap_interpretation"],
        "",
        "COUNTERFACTUAL ANALYSIS:",
        explanation["counterfactual_analysis"],
        "",
        "HEALTH IMPACT:",
        explanation["health_impact_summary"],
        "",
        "RECOMMENDED INTERVENTION:",
        explanation["recommended_intervention"],
    ]

    return "\n".join(lines)


def build_context_for_agent(agent_type: str) -> str:
    """
    Main entry point. Returns context string for the given agent type.
    agent_type: "public" or "policy"
    """
    result = load_result()
    if agent_type == "public":
        return build_public_context(result)
    elif agent_type == "policy":
        return build_policy_context(result)
    else:
        raise ValueError(f"Unknown agent_type: {agent_type}")
